auctions/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", views.index, name="index"),

    # User management
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("search", views.search_category, name="search_category"),
    
    # Listing management
    path("create_listing/", views.create_listing, name="create_listing"),
    path("listing/<int:id>/", views.listing_page, name="listing_page"),
    #path("listing/<int:listing_id>/place_bid/", views.place_bids, name="place_bids"),   # Add initial bid price
    path("listing/list_status_open/<int:id>/", views.listing_is_open, name="listing_is_open"),
    #path("listing/comment/<int:id>/", views.listing_comment, name="listing_comment"),
    
    # Watchlist management
    path("listing/add/<int:id>/", views.add_to_watchlist, name="add_to_watchlist"),
    path("listing/remove/<int:id>/", views.remove_from_watchlist, name="remove_from_watchlist"),
    path('watchlist/', views.view_watchlist, name='view_watchlist'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Model No.1
class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.username

# Model No.2
class AuctionListings(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=64, blank=False, null=False)
    bid_amount = models.FloatField(blank=False)
    #bid_time = models.DateTimeField(default="timezone.now")
    buy_price = models.FloatField(blank=False)
    category = models.CharField(max_length=24, null=True)
    current_highest_bid = models.FloatField(blank=True, null=True) # THIS
    description = models.TextField(blank=False, null=False)
    image = models.FileField(upload_to="uploads/")
    listing_is_open = models.BooleanField(default=True)
    terms_and_condition = models.TextField(blank=True)
    time_date_end = models.DateTimeField(blank=False, null=False)
    starting_bid = models.FloatField(blank=False)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    last_bidder = models.CharField(max_length=64, blank=True, default="Tav"),
    def __str__(self):
        return self.title
    
# Model No.3
class Bid(models.Model):    
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=64, blank=False, null=False, default="untitled")  # Populated from AuctionListings.title
    auction_listing = models.ForeignKey(AuctionListings, on_delete=models.CASCADE, related_name="bids")
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    starting_bid = models.FloatField(blank=False, null=False)
    bid_amount = models.FloatField(blank=False, null=False)
    buy_price = models.FloatField(blank=False, null=False)
    bid_time = models.DateTimeField(auto_now_add=True)
    #current_highest_bid = models.FloatField(blank=True, null=True)
    def __str__(self):
        return self.title

# Model No.4
class Comment(models.Model):
    id = models.BigAutoField(primary_key=True)
    auction_listing = models.ForeignKey(AuctionListings, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField(blank=True)
    comment_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

# Model No.5   
class Watchlist(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    auction_listing = models.ForeignKey(AuctionListings, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

auctions/forms.py
from django import forms 
from .models import AuctionListings, Bid, User, Comment
from django.contrib.auth import get_user_model

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password', 'password_confirm']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError("Passwords do not match")

# To create a new listing.
class AuctionListingForm(forms.ModelForm):
    time_date_end = forms.DateTimeField(widget=forms.TextInput(attrs={
        'id': 'default-datepicker',
        'type': 'text',
        'placeholder': 'Select date'
    }))
    class Meta:
        model = AuctionListings
        fields = ['title', 'image', 'time_date_end', 'description', 'category',
                  'starting_bid', 'bid_amount', 'buy_price']

    def save(self, commit=True):
        auction_listing = super().save(commit=False)
        if commit:
            auction_listing.save()
            Bid.objects.create(
                auction_listing=auction_listing,
                bidder=auction_listing.seller,  # Assuming the seller is the initial bidder
                starting_bid=self.cleaned_data['starting_bid'],
                bid_amount=self.cleaned_data['bid_amount'],
                buy_price=self.cleaned_data['buy_price']
            )
        return auction_listing

# Add initial bidding value while creating a listing    
class BidForm(forms.ModelForm):
    starting_bid = forms.FloatField(required=True)
    bid_amount = forms.FloatField(required=True)
    buy_price = forms.FloatField(required=True)

    class Meta:
        model = Bid
        fields = ['starting_bid', 'bid_amount', 'buy_price']

# To bid price in listing_page. Nevermind the current classes name    
class CurrentHighestBidForm(forms.ModelForm):
    current_highest_bid = forms.FloatField(label="Place your bid")
    class Meta:
        model = Bid
        fields = ['current_highest_bid']
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

auctions/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.db.models import Max
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse

from .forms import UserRegistrationForm, AuctionListingForm, BidForm, CurrentHighestBidForm, CommentForm
from .models import AuctionListings, Bid, Watchlist, Comment

User = get_user_model()

def index(request):
    listing_preview = AuctionListings.objects.all().order_by("-time_date_end")[:8]
    return render(request, "auctions/index.html", {"listing_preview": listing_preview})

def search_category(request):
    if request.method == "POST":
        search_query = request.POST.get('search_query', '')
        search_result = AuctionListings.objects.filter(category__icontains = search_query)
        return render(request, 'auctions/search_category.html', {
            "search_result": search_result, "search_query": search_query
            })  
    else:
        return redirect('index')
        
@login_required
def listing_page(request, id):
    auction_listing = get_object_or_404(AuctionListings, pk=id)
    comments = Comment.objects.filter(auction_listing=auction_listing).order_by('-comment_time')
    
    if request.method == 'POST':
        # For placing new bid
        # Update the current highest bid in the auction listing
        if 'place_bid' in request.POST:
            current_price = 0
            current_price = auction_listing.current_highest_bid
            new_price = current_price + auction_listing.bid_amount
            auction_listing.current_highest_bid = new_price
            
            # Set the latest bidder
            last_bidder = ""
            if current_price == 0:
                auction_listing.last_bidder = auction_listing.seller
            else:
                auction_listing.last_bidder = request.user
            auction_listing.save()
            return redirect('listing_page', id=auction_listing.id)
        
        # For making new comment
        if 'add_comment' in request.POST:        
            comment_form = CommentForm(request.POST) 
            if comment_form.is_valid():
                new_form = comment_form.save(commit=False)
                new_form.auction_listing = auction_listing
                new_form.user = request.user
                new_form.save()
                return redirect('listing_page', id=auction_listing.id)
            else:
                messages.error(request, "Invalid input.")
    else:
        comment_form = CommentForm()
    
    return render(request, 'auctions/listing_page.html', {
        'listing': auction_listing,
        'comment_form': comment_form, # Pass the comment form
        'comments': comments, # Pass the comment
    })
  
@login_required
def create_listing(request):
    if request.method == 'POST':
        form = AuctionListingForm(request.POST, request.FILES)
        bid_form = BidForm(request.POST)
        if form.is_valid():
            auction_listing = form.save(commit=False)
            auction_listing.seller = request.user  # Set the seller to the current user
            auction_listing.save()
            
            return redirect('index')
    else:
        form = AuctionListingForm()
    
    return render(request, 'auctions/create_listing.html', {'form': form,})

# the second page of creating list (adding bid value), not to be confused with bidding higher
# def place_bids(request, listing_id):
    auction_listing = get_object_or_404(AuctionListings, pk=listing_id)
    
    if request.method == 'POST':
        bid_form = BidForm(request.POST)
        if bid_form.is_valid():
            new_bid = bid_form.save(commit=False)
            new_bid.auction_listing = auction_listing
            new_bid.bidder = request.user
            new_bid.save()
            return redirect('index')
    else:
        bid_form = BidForm()
        
    return render(request, 'auctions/place_bids.html', {'bid_form': bid_form, 'listing': auction_listing})

@login_required
def listing_is_open(request, id):
    auction_listing = get_object_or_404(AuctionListings, pk=id)
    
    if request.method == 'POST':
        if request.user == auction_listing.seller:
            if auction_listing.listing_is_open == True: 
                auction_listing.listing_is_open = False
            else:
                auction_listing.listing_is_open = True
            auction_listing.save()
            return redirect('listing_page', id=auction_listing.id)
    else:
        return render(request, 'auctions/listing_page.html', {'listing':auction_listing})

@login_required
def add_to_watchlist(request, id):
    listing = get_object_or_404(AuctionListings, pk=id)
    Watchlist.objects.create(user=request.user, auction_listing=listing)
    
    return redirect('view_watchlist')

@login_required
def remove_from_watchlist(request, id):
    listing = get_object_or_404(AuctionListings, pk=id)
    Watchlist.objects.filter(user=request.user, auction_listing=listing).delete()
    return redirect('view_watchlist')

@login_required
def view_watchlist(request):
    watchlist_items = Watchlist.objects.filter(user=request.user)
    
    return render(request, 'auctions/watchlist.html', {'watchlist_items': watchlist_items})
    
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

#@login_required
#def listing_comment(request, id):
    auction_listing = get_object_or_404(AuctionListings, pk=id)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_form = comment_form.save(commit=False)
            new_form.auction_listing = auction_listing
            new_form.bidder = request.user
            new_form.save()
            return redirect('listing_page', id=auction_listing.id)
    else:
        bid_form = CommentForm()
        
    return render(request, 'auctions/listing_page.html', {'comment_form': comment_form, 'listing': auction_listing})
        
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}
{% load widget_tweaks %}
<!--
    <head>
        <meta charset="UTF-8" />
        <title>Create Listing</title>
    </head>
    
    <body>
        <h1>Create Listing </h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit"></button>
        </form>
    </body>
-->
{% block body %}
        <section class="bg-white dark:bg-gray-900">
            <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
                <h1 class="mb-4 text-3xl font-bold text-gray-900 dark:text-white">Add a new product</h1>
                
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                        <!--title-->
                        <div class="sm:col-span-2">
                            <label for="id_title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Item Name</label>
                            {% render_field form.title placeholder="Item name" required="" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %}

                        </div>
                        <!--image-->
                        <div class="w-full">
                            <label for="id_image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Upload item image</label>
                            {% render_field form.image placeholder="Item image" required="" type="file" class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" placeholder="Product brand" required="" %}
                        </div>
                        <!--starting bid-->
                        <div class="w-full">
                            <label for="id_starting_bid" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Item starting price</label>
                            {% render_field form.starting_bid type="number" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="£3" required="" %}
                        </div>
                        <!--time_date_end-->
                        <div class="w-full">
                        <label for="id_time_date_end" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Item bidding closing date</label>
                            <div class="relative max-w-sm">
                                <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                                  <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                                  </svg>
                                </div>
                                {% render_field form.time_date_end attrs="datepicker" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="31/12/2024" %}
                            </div>
                        </div>
                        <!--bid_amount-->
                        <div>
                            <label for="id_bid_amount" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Item Bidding amount</label>
                            {% render_field form.bid_amount type="number" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="£1" required="" %}
                        </div>
                        <!--category-->
                        <div>
                            <label for="id_category" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Item Category</label>
                            {% render_field form.category type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Banner" required="" %}
                        </div>
                        <!--buy_price-->
                        <div>
                            <label for="id_buy_price" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Item buy out price</label>
                            {% render_field form.buy_price type="number" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="£12" required="" %}
                        </div>
                        <!--description-->
                        <div class="sm:col-span-2">
                            <label for="description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
                            {% render_field form.description rows="8" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Your description here" %}
                        </div>
                    </div>
                    <button type="submit" class="inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center bg-blue-700 hover:bg-blue-800 focus:outline-none text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800">
                        Add product
                    </button>
                </form>
            </div>
          </section>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
        <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
            <!-- Heading & Filters -->
            <div class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8">
            <div>
                <!-- breadcrumbs -->
                <nav class="flex" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                    <li class="inline-flex items-center">
                    <!-- home -->
                    <a href="{% url 'index' %}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-primary-600 dark:text-gray-400 dark:hover:text-white">
                        <svg class="me-2.5 h-3 w-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z" />
                        </svg>
                        Home
                    </a>
                    </li>
                </ol>
                </nav>
                <!-- catalogue title -->
                <h2 class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">{{listing.catalogue}}</h2>
            </div>
            <div class="flex items-center space-x-4">
            </div>
            </div>
            
            <!-- grid template -->
            <div class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4">
            {% for listings in listing_preview %}
            <div class="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">

                <!-- image -->
                <div class="h-56 w-full">
                <a href="{% url 'listing_page' id=listings.id %}">
                    <img class="mx-auto h-full block" src={{listings.image.url}} alt="" />
                </a>
                </div>
        
                <div class="pt-6">
                <!-- title -->
                <a href="{% url 'listing_page' id=listings.id %}" class="text-lg font-semibold leading-tight text-gray-900 hover:underline dark:text-white">{{listings.title}}</a>

                <!-- small note -->
                <ul class="mt-2 flex items-center gap-4">
                    <li class="flex items-center gap-2">
                        <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Current bid:</p>
                    </li>
                </ul>

                <!-- price -->
                <div class="mt-4 flex items-center justify-between gap-4">
                    <p class="text-2xl font-extrabold leading-tight text-gray-900 dark:text-white">£{{listings.current_highest_bid}}</p>
                    <!-- Add to watchlist -->
                    {% if listings.listing_is_open is True %}
                    <form action="{% url 'add_to_watchlist' listings.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="border inline-flex items-center rounded-lg bg-primary-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4  focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                            <svg class="-ms-2 me-2 h-5 w-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4h1.5L8 16m0 0h8m-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm.75-3H7.5M11 7H6.312M17 4v6m-3-3h6" />
                            </svg>
                        Add to watchlist
                        </button>
                    </form>
                    {% endif %} 
                </div>

            </div>
            </div>
            {% endfor %}
            </div>
        </form>
        </section>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

<!-- Tailwind CSS -->
<div class="flex flex-col items-center justify-center px-6 py-2 mx-auto md:h-screen lg:py-0">
  <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">

      <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
        Log in account
      </h1>

      <form class="space-y-4 md:space-y-6" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <!-- Username -->
        <div>
          <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your username</label>
          <input name="username" placeholder="Username" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@flowbite.com" required />
        </div>
        <!-- Password -->
        <div>
          <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>
          <input type="password" name="password" id="password" placeholder="Password" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
        </div>
        <!-- Submit -->
        <button type="submit" value="Register" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          Submit
        </button> 

        <p id="helper-text-explanation" class="text-sm font-light text-gray-500 dark:text-gray-400">
          Don't have an account? 
          <a href="{% url 'register' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">
            Register here.
          </a>
        </p>
      </form>

    </div>
  </div>
</div>

{% endblock %}

<!-- Bootstrap style (unused) -->
<!--
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
    Don't have an account? <a href="{% url 'register' %}">Register here.</a>
-->

auctions/templates/auctions/place_bids.html
<html>
    <head>Place Bid</head>
    <body>
        <h2>Place a Bid on {{ listing.title }}</h2>
        <form method="post">
            {% csrf_token %}
            {{ bid_form.as_p }}
            <button type="submit">Place Bid</button>
        </form>
    </body>
</html>